name: Auto merge
on: pull_request
jobs:
    merge:
        if: ${{ github.actor == 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - id: meta
              uses: dependabot/fetch-metadata@v2
            - name: Auto merge Dependabot PR
              if: |
                steps.meta.outputs.package-ecosystem == 'github_actions'
              run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
