name: Auto merge
on: pull_request
jobs:
    merge:
        if: ${{ github.actor == 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get Metadata
              id: meta
              uses: dependabot/fetch-metadata@v2
              # depandabotが作成したGitHub Action workflowのPRを自動マージ。ただしactionのmajor updateはマージしない
            - name: Auto merge Dependabot PR
              if: |
                steps.meta.outputs.package-ecosystem == 'github_actions' &&
                steps.meta.outcome.update-type != 'version-update:semver-major'
              run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
