name: Change shell
on: push
# shell指定は明示的に行うべき。行わないとpipefail起動オプションが有効にならない
defaults:
    run:
        shell: bash
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${SHELL}"
            - shell: python
              run: |
                import os
                print(os.environ['PATH'])
